- name: tesing dell command module
  hosts: dell,juniper
  become: true
  gather_facts: false
  connection: local
  tasks:
   - dellos10_config:
      lines: ['hostname {{ inventory_hostname }}']
      backup: yes
      backup_options:
       dir_path: /var/lib/rundeck/backup
     when: ansible_network_os == 'dellos10'

   - junos_config:
      backup: yes
      backup_options:
       dir_path: /var/lib/rundeck/backup
     register: juniper
     when: ansible_network_os == 'junos'

 #  - name: Sending mail
 #    mail:
 #     host: alerts.esds.co.in
 #     port: 25
 #     username: automation.config@alerts.esds.co.in
 #     password: K5%48Hxi4T;I
 #     from: automation.config@alerts.esds.co.in
 #     to: shubham.chavan@esds.co.in
 #     subject: Ansible-report
 #     body: System backup of juniper switch has been successfully provisioned.
 #    delegate_to: localhost
 #    when: juniper.changed
 
   #- name: show list of all interfaces
   #  panos_op:
   #   ip_address: 10.11.1.181 
   #   username: esdsnocadmin
   #   password: 7A2e{b92{MA74]_p=p
   #   cmd: 'show system info'
   #  when: ansible_host == '10.11.1.181'
