- name: tesing dell command module
  hosts: testing
  become: true
  gather_facts: false
  connection: local
  tasks:

   - name: Creation of loopback1
     dellos10_config:
      lines:
       - interface loopback 1

   - name: configuration loopback 1
     dellos10_config:
      lines:
       - no shutdown
       - mtu 9212
       - ip address 172.16.12.39/32
      parents: interface loopback 1

   - name: Creation of nve 
     dellos10_config:
      lines:
       - source-interface loopback1
      parents: nve
         
   - name: Creating vlan 
     dellos10_config:
      lines:
       - virtual-network 1825

   - name: VNI creation
     dellos10_config:
      lines: 
       - vxlan-vni 101825
      parents: virtual-network 1825

   - name: vlan creation
     dellos10_config:
      lines:
       - interface vlan 1825
       - description "ESDS"
       - mtu 9100
       - virtual-network 1825
       - no shutdown
       - exit
      parents: interface vlan 1825
     register: vlan

   - name: Configuration of EVPN Parameters
     dellos10_config:
      lines:
       - vni 11825
       - rd 172.16.12.39:1825 
       - route-target 45815:11825 both
      parents:
       - evpn 
       - evi 1825
